# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-difficulty'],
                'verbose_name': '\u0421\u043b\u043e\u0436\u043d\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u0421\u043b\u043e\u0436\u043d\u043e\u0441\u0442\u044c',
            },
        ),
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0447\u043a\u0430')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u043f\u043e\u0445\u043e\u0434\u0430')),
                ('data_finish', models.DateField(blank=True, null=True, verbose_name='\u041a\u043e\u043d\u0435\u0446 \u043f\u043e\u0445\u043e\u0434\u0430')),
                ('state_group', models.SmallIntegerField(choices=[(0, b'\xd0\x93\xd1\x80\xd1\x83\xd0\xbf\xd0\xbf\xd1\x8b \xd0\xbd\xd0\xb5\xd1\x82'), (1, b'\xd0\x93\xd1\x80\xd1\x83\xd0\xbf\xd0\xbf\xd0\xb0 \xd0\xbd\xd0\xb0\xd0\xb1\xd0\xb8\xd1\x80\xd0\xb0\xd0\xb5\xd1\x82\xd1\x81\xd1\x8f'), (2, b'\xd0\x93\xd1\x80\xd1\x83\xd0\xbf\xd0\xbf\xd0\xb0 \xd0\xbd\xd0\xb0\xd0\xb1\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb0')], default=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('status', models.SmallIntegerField(choices=[(0, b'\xd0\x9f\xd0\xbe\xd0\xb4\xd0\xb3\xd0\xbe\xd1\x82\xd0\xbe\xd0\xb2\xd0\xba\xd0\xb0 \xd0\xba \xd0\xbf\xd0\xbe\xd1\x85\xd0\xbe\xd0\xb4\xd1\x83'), (1, b'\xd0\x92 \xd0\xbf\xd0\xbe\xd1\x85\xd0\xbe\xd0\xb4\xd0\xb5'), (2, b'\xd0\x9f\xd0\xbe\xd1\x85\xd0\xbe\xd0\xb4 \xd0\xb7\xd0\xb0\xd0\xb2\xd0\xb5\xd1\x80\xd1\x88\xd0\xb5\xd0\xbd')], default=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('if_comments', models.BooleanField(default=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438 \u0432\u043a\u043b\u044e\u0447\u0435\u043d\u044b')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hike.Difficulty', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
            options={
                'ordering': ['-creation_date'],
                'verbose_name': '\u041f\u043e\u0445\u043e\u0434',
                'verbose_name_plural': '\u041f\u043e\u0445\u043e\u0434\u044b',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-region'],
                'verbose_name': '\u0420\u0435\u0433\u0438\u043e\u043d',
                'verbose_name_plural': '\u0420\u0435\u0433\u0438\u043e\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='TypeHike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_hike', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=b'TypeHikeImage/', verbose_name='\u0422\u0438\u043f \u043f\u043e\u0445\u043e\u0434\u0430 - \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u043f\u043e\u0445\u043e\u0434\u0430',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u043f\u043e\u0445\u043e\u0434\u043e\u0432',
            },
        ),
        migrations.AddField(
            model_name='hike',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hike.Region', verbose_name='\u0420\u0430\u0439\u043e\u043d \u043f\u043e\u0445\u043e\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='hike',
            name='type_hike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hike.TypeHike', verbose_name='\u0422\u0438\u043f \u043f\u043e\u0445\u043e\u0434\u0430'),
        ),
        migrations.AddField(
            model_name='hike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.CustomUser', verbose_name='\u0420\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c'),
        ),
    ]
