# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-03 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirs',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='Materials', to='materials.Material', verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u044b'),
        ),
        migrations.AlterField(
            model_name='material',
            name='karma_users',
            field=models.ManyToManyField(blank=True, related_name='user_karma_materials', to='profile.CustomUser', verbose_name='\u041b\u044e\u0434\u0438 \u0441\u0434\u0435\u043b\u0430\u043b\u0438 \u043e\u0442\u043c\u0435\u0442\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_edit',
            field=models.ManyToManyField(blank=True, related_name='material_edit', to='materials.MaterialEdit', verbose_name='\u0420\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
