# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('force_blog', '0002_blogpost_view_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultImageParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=b'DefaultImageParty/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e',
                'verbose_name_plural': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u043f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u041c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u0435')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateTimeField(verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u044f')),
                ('data_finish', models.DateTimeField(verbose_name='\u041a\u043e\u043d\u0435\u0446 \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u044f')),
                ('state', models.SmallIntegerField(choices=[(0, b'\xd0\x92\xd1\x8b\xd0\xba\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xbd\xd0\xbe'), (1, b'\xd0\x92\xd0\xba\xd0\xbb\xd1\x8e\xd1\x87\xd0\xb5\xd0\xbd\xd0\xbe')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('type_party', models.SmallIntegerField(choices=[(1, b'\xd0\x92\xd1\x81\xd1\x82\xd1\x80\xd0\xb5\xd1\x87\xd0\xb0'), (0, b'\xd0\x9c\xd0\xb5\xd1\x80\xd0\xbe\xd0\xbf\xd1\x80\xd0\xb8\xd1\x8f\xd1\x82\xd0\xb8\xd0\xb5')], default=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('text', redactor.fields.RedactorField(verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0447\u043a\u0430')),
                ('short_desc', models.CharField(max_length=250, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435(\u0441\u043d\u043e\u0441\u043a\u0430)')),
                ('image', models.ImageField(upload_to=b'PartyImages/')),
                ('if_comments', models.BooleanField(default=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438 \u0432\u043a\u043b\u044e\u0447\u0435\u043d\u044b')),
                ('category', models.ManyToManyField(related_name='party_category', to='force_blog.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438')),
                ('default_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='party.DefaultImageParty', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e')),
            ],
            options={
                'ordering': ['date_start'],
                'verbose_name': '\u041c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u0435',
                'verbose_name_plural': '\u041c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u044f',
            },
        ),
    ]
