# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 12:16
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True, verbose_name='\u041f\u0440\u043e \u0441\u0435\u0431\u044f')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('karma', models.SmallIntegerField(default=50, verbose_name='\u041a\u0430\u0440\u043c\u0430')),
                ('avatar', django_resized.forms.ResizedImageField(default=b'avatars/no_avatar.png', upload_to=b'avatars/')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440')),
                ('vk', models.CharField(blank=True, max_length=90, null=True, verbose_name='VK')),
                ('facebook', models.CharField(blank=True, max_length=90, null=True, verbose_name='Facebook')),
                ('od_class', models.CharField(blank=True, max_length=90, null=True, verbose_name='\u041e\u0434\u043d\u043e\u043a\u043b\u0430\u0441\u0441\u043d\u0438\u043a\u0438')),
                ('writer', models.BooleanField(default=False, verbose_name='\u041f\u0438\u0441\u0430\u0442\u0435\u043b\u044c')),
                ('valid_member', models.BooleanField(default=False, verbose_name='\u0414\u0435\u0439\u0441\u0442\u0432\u0438\u043b\u044c\u043d\u044b\u0439 \u0447\u043b\u0435\u043d')),
                ('moderator', models.BooleanField(default=False, verbose_name='\u041c\u043e\u0434\u0435\u0440\u0430\u0442\u043e\u0440')),
                ('goverment', models.BooleanField(default=False, verbose_name='\u041f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0435')),
                ('instructor', models.BooleanField(default=False, verbose_name='\u0418\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440')),
                ('black', models.BooleanField(default=False, verbose_name='Black')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
