# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('force_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='view_user',
            field=models.BooleanField(default=False, verbose_name='\u0423\u043a\u0430\u0437\u0430\u0442\u044c \u0430\u0432\u0442\u043e\u0440\u0430?'),
        ),
    ]
