# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('info_pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopage',
            name='url_link',
        ),
        migrations.AddField(
            model_name='infopage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Meta descriptoin'),
        ),
        migrations.AddField(
            model_name='infopage',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='infopage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='infopage',
            name='meta_url',
            field=models.CharField(default=datetime.datetime(2016, 3, 19, 10, 19, 59, 117000, tzinfo=utc), max_length=100, verbose_name='Meta url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infopage',
            name='if_comments',
            field=models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0435\u0432'),
        ),
    ]
