# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_pages', '0002_auto_20160319_1219'),
        ('info_pages', '0002_auto_20151130_1610'),
    ]

    operations = [
    ]
